services:

  mingei_app:
    container_name: mingei_app
    build: ./docker/php
    volumes:
     - .:/var/www

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - mingei_app

  mingei_db:
    image: mysql:5.7
    container_name: mingei_db
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: mingeidatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  mingei_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mingei_db
      - PMA_USER=root
      - PMA_PASSWORD=root_pw
    depends_on:
      - mingei_db
    links:
      - mingei_db
    ports:
      - 4040:80
